[package]
name = "nesrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
bitflags = "2.4.2"
cpal = "0.15.3"
env_logger = "0.11.3"
error-iter = "0.4.1"
log = "0.4.21"
modular-bitfield = "0.11.2"
pixels = "0.13.0"
rusttype = "0.9.3"
strum_macros = "0.26.1"
winit = { version = "0.29.15", features = ["rwh_05"] }
winit_input_helper = "0.16.0"
