# Simple workflow for deploying static content to GitHub Pages
name: Deploy WASM build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack 
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Build WASM target
        working-directory: ./emu-wasm
        run: wasm-pack build
        
      - name: Set up Node
        uses: actions/setup-node@v4
        working-directory: ./web
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Build
        working-directory: ./web
        run: npm run build

      - name: Setup Pages
        working-directory: ./web
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: 'web/dist'

      - name: Deploy to GitHub Pages
        working-directory: ./web
        id: deployment
        uses: actions/deploy-pages@v4
